### ISSUE TITLE
cthread back end quits if NMC_NUM_THREADS not set

### ISSUE THREAD

**Issue by bcumming** [eth-cscs/nestmc-proto#197]
This is very annoying, and differs from the other threading models that do not require that an environment variable be set.

I propose:
  * setting the default number of threads to be 1
  * printing a warning at startup if the environment variable has not been set

A more advanced option would be to detect how many core the process has affinity with, and automatically set the number of threads to use all available cores, unless the user explicitly specifies a core count via `NMC_NUM_THREADS`.

**Comment by bcumming** [comment]
The `global_get_num_threads` function in the cthread back end also causes the Intel compiler to choke on:
```
162     auto nthreads_str_end{nthreads_str};
```
because it deduces the type of `nthreads_str` to be `std::initializer_list<const char*>`.

While we are fixing this issue, we should clean this up to just use `std::stoi`.

**Comment by apeyser** [comment]
Other threading models are capable of determining a reasonable number of threads automatically. So I chose to fail when unset, because almost always that is actually an error. But I'm not ideologically commited to it -- I just wanted the code to fail immediately when I forgot to set it, rather than having to figure it out from the strange behavior of the simulation.

So, figuring out a reasonable way to figure out a reasonable default would be a better solution.

I thought I had changed the nthreads_str_end setting -- the behavior with std::initializer_list is confusing even to compiler writers. That should be fixed.

**Comment by bcumming** [comment]
I have a PR that simply uses one thread and prints a warning message if the variable is not set.

Detecting the available cores is not too hard on the linux systems I have used, but I don't know if that is a generally straightforward problem to solve.

Should I make a new ticket to try to set a reasonable number of threads according to thread affinity?
