### ISSUE TITLE
First exploration of methods

### ISSUE THREAD

**Issue by bcumming** [eth-cscs/nestmc-proto#70]
* matrix-vector multiplication implementation for Hines matrix                                       
    * Conjugate Gradient solver
    * develop simple performance model for the GPU for both Hines method and CG
    * investigate impact of naive Jacobi preconditione

**Comment by pedrovalerolara** [comment]
BSC (Pedro and Ivan) has developed several prototypes to compute the Hines methods on GPUs.
Second item of the previous comment.
Different data layouts have been tested.
As overview, the performance obtained by the best of the GPU prototypes (on one of the K40 CUDA GPUs in one K80 GPUs) already implemented is about 3.25x faster than 2xIntel Xeon E5-2630v3 (Haswell) (8 cores each) 
For more details, we attached some slides.
[24-11-2016.pdf](https://github.com/eth-cscs/nestmc-proto/files/627107/24-11-2016.pdf)

**Comment by pedrovalerolara** [comment]
We have explored the use of MultiGPU for computing multiple Hines systems in parallel. As shown (slides attached) we achieve close to an ideal scaling (2xGPUs = 2xFaster). Also, to evaluate the performance and benefit of our approach to compute multiple Hines systems using one thread per systems instead of one CUDA block per system, we implemented a Thomas algorithm similar to our Hines implementation (by interleaving the elements form different systems). We compared this Thomas implementation against gtvsStridedBatch routine of cuSPARSE, which uses one CUDA block per system and parallel methods based on Cyclic-Reduction to solve Tridiagonal systems. As shown, our approach beats the performance achieved by the cuSPARSE routine from 2000 number of systems, being close to 3x faster.
[03-02-2017_1.pdf](https://github.com/eth-cscs/nestmc-proto/files/750706/03-02-2017_1.pdf)
